---
title: "Structuring around exemplars - ESIDA workshop"
author: "Joris Falip"
date: "12/2018"
output: html_document
params:
   
   data_str: "housing"
   k: 124
   threshold: 10
   range: 371
   nb_cpus: 4
editor_options: 
  chunk_output_type: console
---

# Objectives


```{r setup, include=FALSE}
knitr::opts_chunk$set()

library(fields)
library(foreach)
library(doParallel)
library(magrittr)
library(ggplot2)
library(readxl)
library(readr)
library(telegram)
library(tictoc)
library(purrr)
library(pryr)
library(igraph)

source("structuration.R")

registerDoParallel(params$nb_cpus)

bot <- TGBot$new(token = bot_token('Elesbot'))
bot$set_default_chat_id(user_id('me'))
```

```{r data, include=FALSE}
#Chargement des données

if (params$data_str == "housing") {
  ### RESIDENTIAL ###
  # https://archive.ics.uci.edu/ml/datasets/Residential+Building+Data+Set
  
  housing <- read_excel("data/Residential-Building-Data-Set.xlsx", 
                 sheet = "Data", col_names = FALSE, col_types = c("blank", 
                                                                  "blank", "blank", "blank", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric", "numeric", 
                                                                  "numeric", "numeric"), skip = 2)
  
  data <- as.matrix(housing)
  soluce <- data[ ,105]
  data <- data[ ,-105]
  data <- data[ ,-104]
  
  rm(housing)
}


if (params$data_str == "crime") {
  ### CRIME ###
  # http://archive.ics.uci.edu/ml/datasets/Communities+and+Crime+Unnormalized
  
  crime <- read_csv("data/CommViolPredUnnormalizedData.txt", col_names = FALSE, na = "?")
  
  data <- crime[ ,-c(1:5)]
  data <- as.matrix(data)
  soluce <- crime$X131
  data <- data[ ,1:124]
  colToKeep <- colSums(is.na(data)) > 0
  data <- data[ ,!colToKeep]
  
  rm(crime,colToKeep)
}

if(params$data_str == "patients") {
  ### PATIENTS ###
  
  source("cleaning-patients.R")
  
  data <- as.matrix(tidy)
  colSelect <- which(colnames(data) == "cd_hb_a1c")
  data <- data[1:300,]
  soluce <- data[which(data[, colSelect] > 0),colSelect]
  data <- data[which(data[, colSelect] > 0),-colSelect]
}
```



```{r prediction-joris}
results_exemplars <- structuration(data, params$k, params$threshold)
exemplars_graph <- make_graph(as.vector(rbind(1:length(results_exemplars), results_exemplars)))
plot(exemplars_graph, vertex.size = 3, edge.arrow.size = 0.1)


```



```{r nearest-minkowski}
distance_matrix <- as.matrix(dist(scale(data), method = "minkowski", p = 0.75))
results_minkowski <- integer(dim(data)[1])
diag(distance_matrix) <- 9999999
for (elem in 1:dim(data)[1]) {
  results_minkowski[elem] <- which(distance_matrix[elem,] == min(distance_matrix[elem,]))
}

mink_graph <- make_graph(as.vector(rbind(1:dim(data)[1], results_minkowski)))
plot(mink_graph, vertex.size = 3, edge.arrow.size = 0.1, vertex.label = "")
components(mink_graph)$no
mean(components(mink_graph)$csize)
mean(unlist(lapply(decompose(mink_graph), diameter)))
```



```{r evolution-composantes}
registerDoParallel(params$nb_cpus)

composantes <- foreach(i = 1:params$range) %dopar% {
  results_components <- structuration(data, i, params$threshold)

  resgraph <- make_graph(as.vector(rbind(seq_len(dim(data)[1]), results_components)))
  return(components(resgraph)$no)
}

composantes <- unlist(composantes)
df <- as.data.frame(composantes)

composantes_graphs <- ggplot(df, aes(1:params$range)) + 
  geom_line(aes(y = composantes, color = "joris")) +
  labs(x = "Input parameter K", y = "Number of connected components")
composantes_graphs + theme_pubr() + grids(linetype = "dashed") + theme(legend.position = "none")

stopImplicitCluster()
```